NextGenAppPackage/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NextGenAppPackage/main/default/objects/Applicant__c/fields/PossibleStartDate__c.field-meta.xml
<CustomField>
    <fullName>PossibleStartDate__c</fullName>
    <label>Possible Start Date</label>
    <type>Date</type>
</CustomField>

NextGenAppPackage/main/default/classes/ApplicantTrHdl.cls
public class ApplicantTrHdl {

    public void  beforeInsert(List<Applicant__c> newList){
        doThingsBefore (newList);
    }
    
    private void doThingsBefore(List<Applicant__c>newLIst){
        
        for (Applicant__c a : newlist){
            //check Start Date
            if (a.PossibleStartDate__c<System.today()){
                a.possibleStartDate__c=System.today();
            }
            //set department
            a.Department__c='Sales Development';
        }
    }
    
}